# Generated by Django 5.0.6 on 2025-04-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_remove_chat_content_alter_chat_title_alter_chat_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("init", "Initial Prompt"),
                            ("generate_mvp", "Generate MVP"),
                            ("debate", "Critique MVP"),
                            ("finalize_mvp", "Finalize MVP"),
                            ("design", "Design Guidelines"),
                            ("tech_stack", "Tech Stack Recommendation"),
                            ("complete", "Completed"),
                        ],
                        default="init",
                        max_length=50,
                    ),
                ),
                ("product_description", models.TextField(blank=True, null=True)),
                ("mvp", models.TextField(blank=True, null=True)),
                ("critiques", models.JSONField(blank=True, null=True)),
                ("final_mvp", models.TextField(blank=True, null=True)),
                ("design_guidelines", models.TextField(blank=True, null=True)),
                ("tech_stack", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="chat.chat",
                    ),
                ),
            ],
        ),
    ]
