# Generated by Django 5.0.6 on 2025-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_repo_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="github_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
