# Generated by Django 5.0.6 on 2025-04-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_github_repo_name_project_github_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deployed_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("init", "Initial Prompt"),
                    ("generate_mvp", "Generate MVP"),
                    ("debate", "Critique MVP"),
                    ("finalize_mvp", "Finalize MVP"),
                    ("design", "Design Guidelines"),
                    ("tech_stack", "Tech Stack Recommendation"),
                    ("development", "Development"),
                    ("test", "Testing"),
                    ("deploy", "Deployment"),
                    ("complete", "Completed"),
                ],
                default="init",
                max_length=50,
            ),
        ),
    ]
