# Generated by Django 5.0.6 on 2025-10-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_deployed_url_alter_project_current_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages_approved", models.BooleanField(default=False)),
                ("pages", models.JSONField(blank=True, default=list, null=True)),
                ("prompts", models.JSONField(blank=True, null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_development_stage",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="development_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_development",
                to="projects.developmentstage",
            ),
        ),
    ]
