# Generated by Django 5.0.6 on 2025-10-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_developmentstage_project_development_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="critiques",
        ),
        migrations.RemoveField(
            model_name="project",
            name="final_mvp",
        ),
    ]
