# Generated by Django 5.0.6 on 2025-10-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_critiques_remove_project_final_mvp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="development_stage",
        ),
        migrations.AlterField(
            model_name="developmentstage",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="development_stage",
                to="projects.project",
            ),
        ),
    ]
